/****** Script for SelectTopNRows command from SSMS  ******/
SELECT DISTINCT --,[ProspectiveBuyerKey]
      --,[ProspectAlternateKey]
      --,[FirstName]
      --,[MiddleName]
      --,[LastName]
      --,[BirthDate]
      --,[MaritalStatus]
      --,[Gender]
      --,[EmailAddress]
      --,[YearlyIncome]
      --,[TotalChildren]
      --,[NumberChildrenAtHome]
      --,[Education]
      Occupation
      --,[HouseOwnerFlag]
      --,[NumberCarsOwned]
      --,[AddressLine1]
      --,[AddressLine2]
      --,[City]
      --,[StateProvinceCode]
      --,[PostalCode]
      --,[Phone]
      --,[Salutation]
     -- ,[Unknown]
  FROM [AdventureWorksDW2019].[dbo].[ProspectiveBuyer]