/****** Script for SelectTopNRows command from SSMS  ******/
SELECT COUNT (DISTINCT CalendarYear ) --,[DateKey]
      --,[FullDateAlternateKey]
      --,[DayNumberOfWeek]
      --,[EnglishDayNameOfWeek]
      --,[SpanishDayNameOfWeek]
      --,[FrenchDayNameOfWeek]
      --,[DayNumberOfMonth]
      --,[DayNumberOfYear]
      --,[WeekNumberOfYear]
      --,[EnglishMonthName]
      --,[SpanishMonthName]
      --,[FrenchMonthName]
     -- ,[MonthNumberOfYear]
      --,[CalendarQuarter]
      --,[CalendarYear]
      --,[CalendarSemester]
      --,[FiscalQuarter]
      --,[FiscalYear]
      --,[FiscalSemester]
  FROM [AdventureWorksDW2019].[dbo].[DimDate]