/****** Script for SelectTopNRows command from SSMS  ******/
SELECT COUNT  (DISTINCT Amount) --,[FinanceKey]
      --,[DateKey]
      --,[OrganizationKey]
      --,[DepartmentGroupKey]
      --,[ScenarioKey]
      --,[AccountKey]
      --,[Amount]
      --,[Date]
  FROM [AdventureWorksDW2019].[dbo].[FactFinance]