/****** Script for SelectTopNRows command from SSMS  ******/
SELECT DepartmentName,BaseRate,Gender, --,[EmployeeKey]
      --,[ParentEmployeeKey]
      --,[EmployeeNationalIDAlternateKey]
      --,[ParentEmployeeNationalIDAlternateKey]
      --,[SalesTerritoryKey]
      --,[FirstName]
      --,[LastName]
      --,[MiddleName]
      --,[NameStyle]
      --,[Title]
      --,[HireDate]
      --,[BirthDate]
      --,[LoginID]
     -- ,[EmailAddress]
     -- ,[Phone]
      --,[MaritalStatus]
     -- ,[EmergencyContactName]
     -- ,[EmergencyContactPhone]
      --,[SalariedFlag]
      --,[Gender]
     -- ,[PayFrequency]
      --,[BaseRate]
      --,[VacationHours]
      --,[SickLeaveHours]
     -- ,[CurrentFlag]
      --,[SalesPersonFlag]
      --,[DepartmentName]
      --,[StartDate]
     -- ,[EndDate]
      --,[Status]
     --,[EmployeePhoto]
	 CASE 
	 WHEN BaseRate > 30 THEN  'Over paid'
	 ELSE 'under paid'
	 END AS Comment
  FROM [AdventureWorksDW2019].[dbo].[DimEmployee]