/****** Script for SelectTopNRows command from SSMS  ******/
SELECT CustomerKey,
     GeographyKey,
      CustomerAlternateKey,
      Title,
      FirstName,
      MiddleName,
      LastName,
      NameStyle,
      BirthDate,
      MaritalStatus,
      Suffix,
      Gender,
      EmailAddress,
      YearlyIncome,
      TotalChildren,
      NumberChildrenAtHome,
      EnglishEducation,
      SpanishEducation,
      FrenchEducation,
      EnglishOccupation,
      SpanishOccupation,
      HouseOwnerFlag,
      NumberCarsOwned,
      AddressLine1,
      AddressLine2,
      Phone,
      DateFirstPurchase,
      CommuteDistance
  FROM [AdventureWorksDW2019].[dbo].[DimCustomer]
  WHERE YearlyIncome >=60000;